### PR TITLE
Added endpoints for prototyping and testing

### PR DESCRIPTION
**Pull request by lloyddewit**
Added an endpoint for the `inventory_table` product.
The end point returns the result as a JSON string.
The endpoint can be tested with the parameters below.
Note that the `data` parameter is not currently used. Instead, the `daily_niger` data set is currently always used.
If you wish to test the endpoint, then you can use the test data below.
```
{
  "data": "string",
  "date_time": "date",
  "elements": [
    "rain"
  ],
  "station": "station_name",
  "year": "year",
  "month": "month",
  "day": "day",
  "missing_indicator": "M",
  "observed_indicator": "X"
}
```

### CODE REVIEW

**Comment by lloyddewit** [comment]
I also added an endpoint for `timeseries_plot`. This returns a streamed JPEG.
Suggested test data:
```
{
  "data": "string",
  "date_time": "date",
  "elements": "tmax",
  "station": "station_name",
  "facet_by": "stations",
  "type": "line",
  "add_points": false,
  "add_line_of_best_fit": false,
  "se": true,
  "add_path": false,
  "add_step": false,
  "na_rm": false,
  "show_legend": true,
  "title": "Timeseries Plot",
  "x_title": "string",
  "y_title": "string"
}
```

**Comment by lloyddewit** [comment]
Added endpoint for `climatic_summary`. This returns a data frame.
Suggested test data:

```
{
  "data": "string",
  "date_time": "date",
  "station": "station_name",
  "elements": ["rain"],
  "year": "year",
  "month": "month",
  "to": "monthly",
  "by": "station_name",
  "summaries": {
    "mean": "mean", "st_dv": "sd", "n_na": "naflex::na_n"
  }
}
```

**Review by chrismclarke — APPROVED** [review]
Thanks for the demo today and updates @lloyddewit 

I tried checking out and running locally, the updated readme was very useful to have so thanks for that. I still had a couple issues to resolve, so have included a few updates:

- Remove the `backports.zoneinfo` package. This was causing a lot of problems for me, and reading around it appears to not be required if `tzdata` is present (which we have) and/or if using python >= 3.9 (I'm running on 3.10). It appears to just be a temporary bug for python 3.10 which is why I just couldn't get it working. Let me know if this causes any issues for you

Links to issues:
https://dev.to/shriekdj/python-failed-building-wheel-for-backportszoneinfo-on-linux-2mo8
https://github.com/pganssle/zoneinfo/issues/105

- Moved `rinstat` folder to root (as otherwise would only import on my system if namespace as app.rinstat which is less portable for when we have published as package. I don't expect this to have any knock-ons 

- Added a `install_packages.R` script to facilitate installing from cloud environment (without user input, hence why default repo also specified) and included the `rlang`. Again, I assume this is something that other machines have globally but mine just do not.

I hope none of these have knock-ons for you. Please let me know if any further changes are required to maintain compatibility across systems

In addition I've made a few additional changes:
- Updated the `DOCKERFILE` to install R and compile relevant packages. This was a bit tricky as there are a lot of additional dependencies assumed installed (e.g. build tools that may/may not come with various os). I originally tried using an ubuntu image and installing everything from fresh however the build process took ages and was overly bloated so I've since refined and all seems to be working with Debian 11 (bullseye). You can take a look at the dockerfile to see the actual installed dependencies, I'm still not sure if all are required but happy to leave as is for now.

- Updated docs to support installation on windows

- Added the test snippets you included to the codebase for ease of access, and moved the test data to the same folder for tidiness

But overall great to have this working, a really like the use of classes for the API endpoints and the test data you've provided so we can see how things are likely to run in the future. Also really good to have the various python/R dependencies up and running as they definitely had the potential to become a time-sink if not configured correctly

**Comment by lloyddewit** [comment]
@chrismclarke Thank you, excellent progress.
I pulled from the updated main branch and the server runs correctly.
The only side-effect I had is that the debugger no longer works. This is because the debugger runs a specific file (`main.py`) and it imports relative from this file. Therefore it cannot find the `rinstat` module because the associated directory is now one level higher. I tried specifying a relative import but this also did not work. I couldn't find a solution online so the workaround I am using is to have an `app/rinstat` directory temporarily while I'm debugging. There's probably a smarter way of doing this but this works for now.
For a production server, we would likely publish cdms_products as a Python package, then this problem should disapear.
I will add a separate note to `README.md` in a separate PR.

**Pull request merged**
